spring:
  application:
    name: rooms_management

  datasource:
    url: jdbc:mysql://localhost:3306/Room_management_system?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: "root1234"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  eureka:
    client:
      serviceUrl:
        defaultZone: http://74.249.8.84:8761/eureka/

  management:
    tracing:
      sampling:
        probability: 1.0

server:
  port: 8084
